export const mockData = {
  summary: {
    total: {
      equity: 1450780.2,
      pnlPct: 5.8,
      dayPnL: 18240.32,
      exposure: 64,
      unrealized: 79650.15,
      realizedToday: 12450.4,
      spark: [12, 18, 16, 24, 28, 26, 32, 36, 40, 38, 44, 52],
    },
    stocks: {
      equity: 820500,
      cash: 250280.2,
      pnlPct: 4.91,
      exposure: 41,
      spark: [16, 18, 20, 22, 21, 24, 28, 30, 33, 31, 36, 39],
    },
    crypto: {
      equity: 630280.2,
      quoteBalance: 142250.4,
      pnlPct: 6.25,
      exposure: 23,
      spark: [10, 12, 13, 12, 15, 16, 18, 22, 24, 23, 26, 30],
    },
  },
  stockLeaderboard: [
    { rank: 1, symbol: 'NVDA', move: 4.1 },
    { rank: 2, symbol: 'AAPL', move: 1.9 },
    { rank: 3, symbol: 'MSFT', move: 1.9 },
    { rank: 4, symbol: 'TSLA', move: 1.7 },
    { rank: 5, symbol: 'PLTR', move: 1.5 },
  ],
  cryptoLeaderboard: [
    { rank: 1, symbol: 'SOL', move: 7.2 },
    { rank: 2, symbol: 'ETH', move: 1.2 },
    { rank: 3, symbol: 'BTC', move: 2.5 },
    { rank: 4, symbol: 'DOGE', move: 0.8 },
    { rank: 5, symbol: 'AVAX', move: 3.4 },
  ],
  positions: [
    {
      symbol: 'ETH',
      side: 'Buy',
      qty: 30,
      entry: 250,
      last: 280.9,
      pnl: 20500,
      asset: 'Crypto',
      venue: 'Kraken',
      account: 'Live',
      strategy: 'VWAP Reclaim',
      status: 'Managed',
      stop: 235,
      stopRule: 'Step trailing',
      target: 'Trail into strength',
      enteredAt: '2026-03-14 09:41:00',
      fees: 22.32,
      exposure: 12,
      regime: 'Bull',
      events: ['Stop ratcheted', 'Size verified', 'Broker sync clean'],
    },
    {
      symbol: 'NVDA',
      side: 'Buy',
      qty: 100,
      entry: 20,
      last: 23.9,
      pnl: 76550,
      asset: 'Stock',
      venue: 'Public',
      account: 'Paper',
      strategy: 'Trend Pullback',
      status: 'Managed',
      stop: 18.9,
      stopRule: 'Trailing',
      target: 'ATR extension zone',
      enteredAt: '2026-03-13 10:10:00',
      fees: 4.21,
      exposure: 18,
      regime: 'Bull',
      events: ['Risk gate accepted', 'Stop updated', 'PnL snapshot recorded'],
    },
    {
      symbol: 'TSLA',
      side: 'Sell',
      qty: 10,
      entry: 20,
      last: 39.95,
      pnl: -155.55,
      asset: 'Stock',
      venue: 'Public',
      account: 'Paper',
      strategy: 'Opening Range Breakout',
      status: 'Mismatch',
      stop: 18.4,
      stopRule: 'Fixed stop',
      target: '2R partial then trail',
      enteredAt: '2026-03-14 10:03:00',
      fees: 1.18,
      exposure: 7,
      regime: 'Neutral',
      events: ['Broker qty drift warning', 'Reconcile queued', 'Alert unread'],
    },
    {
      symbol: 'AAPL',
      side: 'Buy',
      qty: 40,
      entry: 15,
      last: 15.1,
      pnl: 733.35,
      asset: 'Stock',
      venue: 'Alpaca',
      account: 'Paper',
      strategy: 'VWAP Reclaim',
      status: 'Managed',
      stop: 14.2,
      stopRule: 'Fixed stop',
      target: 'Opening drive continuation',
      enteredAt: '2026-03-14 09:55:00',
      fees: 0.82,
      exposure: 5,
      regime: 'Bull',
      events: ['Entry confirmed', 'Stop posted', 'No issues'],
    },
  ],
  performance: {
    total: {
      sharpe: '2.05',
      drawdown: 7.8,
      spark: [10, 11, 14, 12, 15, 18, 19, 18, 22, 24, 23, 28],
    },
    stock: {
      sharpe: '2.15',
      alpha: 8.2,
      jensen: 7.1,
      drawdown: 5.7,
      spark: [12, 13, 14, 15, 17, 19, 18, 21, 23, 24, 26, 29],
    },
    crypto: {
      sharpe: '1.88',
      alpha: 10.5,
      jensen: 9.3,
      drawdown: 15.2,
      spark: [8, 10, 9, 11, 12, 15, 17, 16, 18, 22, 24, 26],
    },
    metrics: [
      { label: 'Win Rate', value: '63%', tone: 'positive' },
      { label: 'Profit Factor', value: '1.84', tone: 'violet' },
      { label: 'Sortino', value: '2.31', tone: 'amber' },
      { label: 'Expectancy', value: '$48.20', tone: 'positive' },
      { label: 'Avg Win', value: '$112.40', tone: 'neutral' },
      { label: 'Avg Loss', value: '-$61.10', tone: 'warning' },
    ],
    stockLeaders: [
      { rank: 1, symbol: 'NVDA', returnPct: 15.5 },
      { rank: 2, symbol: 'PLTR', returnPct: 13.2 },
      { rank: 3, symbol: 'META', returnPct: 11.8 },
      { rank: 4, symbol: 'AAPL', returnPct: 10.4 },
    ],
    cryptoLeaders: [
      { rank: 1, symbol: 'SOL', returnPct: 8.2 },
      { rank: 2, symbol: 'BTC', returnPct: 5.5 },
      { rank: 3, symbol: 'ETH', returnPct: 4.1 },
      { rank: 4, symbol: 'ADA', returnPct: 3.6 },
    ],
  },
  stockUniverse: [
    {
      rank: 1,
      symbol: 'NVDA',
      last: 820.3,
      changePct: 2.6,
      composite: 96,
      liquidity: 94,
      participation: 91,
      trend: 97,
      eligibility: 'Eligible',
      why: 'High liquidity, strong trend, acceptable spread, regime aligned.',
      blocker: '',
      lastRefresh: '2m ago',
      spark: [12, 14, 17, 18, 22, 24, 25, 29, 31, 32],
    },
    {
      rank: 2,
      symbol: 'AMZN',
      last: 220,
      changePct: -0.5,
      composite: 88,
      liquidity: 92,
      participation: 84,
      trend: 80,
      eligibility: 'Cooling Down',
      why: 'Still strong on liquidity, but short-term thrust softened.',
      blocker: 'Momentum reset pending',
      lastRefresh: '2m ago',
      spark: [18, 17, 16, 17, 18, 19, 18, 17, 19, 20],
    },
    {
      rank: 3,
      symbol: 'AAPL',
      last: 195.42,
      changePct: 1.2,
      composite: 84,
      liquidity: 95,
      participation: 79,
      trend: 78,
      eligibility: 'Eligible',
      why: 'Broad participation and healthy cash-session volume.',
      blocker: '',
      lastRefresh: '2m ago',
      spark: [9, 10, 12, 13, 12, 14, 15, 17, 19, 20],
    },
  ],
  cryptoUniverse: [
    {
      rank: 1,
      symbol: 'BTC/USD',
      last: 68320.4,
      changePct: 1.7,
      composite: 98,
      liquidity: 99,
      participation: 95,
      trend: 94,
      eligibility: 'Eligible',
      why: 'Anchor asset, strongest breadth contribution.',
      blocker: '',
      lastRefresh: '3m ago',
      spark: [18, 21, 22, 24, 23, 27, 28, 30, 31, 34],
    },
    {
      rank: 2,
      symbol: 'ETH/USD',
      last: 3810.5,
      changePct: 0.9,
      composite: 95,
      liquidity: 96,
      participation: 92,
      trend: 91,
      eligibility: 'Eligible',
      why: 'Clean structure with healthy spread and participation.',
      blocker: '',
      lastRefresh: '3m ago',
      spark: [12, 12, 14, 15, 17, 18, 19, 21, 24, 26],
    },
    {
      rank: 3,
      symbol: 'SOL/USD',
      last: 182.3,
      changePct: 4.3,
      composite: 87,
      liquidity: 83,
      participation: 89,
      trend: 90,
      eligibility: 'Data Stale',
      why: 'Structure is strong, but one candle sync lagged.',
      blocker: 'Freshness threshold breached',
      lastRefresh: '18m ago',
      spark: [10, 13, 16, 15, 18, 20, 22, 24, 28, 31],
    },
  ],
  strategyRows: [
    {
      rank: 1,
      symbol: 'GOOGL',
      primaryStrategy: 'VWAP Strategy',
      secondaryStrategy: 'Trend Pullback',
      readiness: 97,
      status: 'Ready',
      regime: 'Bull',
      passed: ['Trend filter', 'Liquidity gate', 'Opening structure'],
      failed: ['None'],
      reason: 'All pillars aligned. Entry trigger is one clean reclaim away.',
      nextEvaluation: 'in 3 minutes',
    },
    {
      rank: 2,
      symbol: 'AMZN',
      primaryStrategy: 'Trend Follower v1',
      secondaryStrategy: 'Opening Range Breakout',
      readiness: 94,
      status: 'Near Ready',
      regime: 'Bull',
      passed: ['Regime', 'Breadth alignment'],
      failed: ['Volume burst confirmation'],
      reason: 'Setup is built, but the tape still owes one more burst of confirmation.',
      nextEvaluation: 'in 4 minutes',
    },
    {
      rank: 3,
      symbol: 'META',
      primaryStrategy: 'Mean Reversion',
      secondaryStrategy: 'VWAP Reclaim',
      readiness: 92,
      status: 'Blocked',
      regime: 'Neutral',
      passed: ['Liquidity', 'Volatility'],
      failed: ['Regime mismatch'],
      reason: 'Quality is fine. Market backdrop is not singing the same song.',
      nextEvaluation: 'in 5 minutes',
    },
  ],
  cryptoStrategies: [
    {
      rank: 1,
      symbol: 'BTC',
      primaryStrategy: 'Trend Follower',
      secondaryStrategy: 'Breakout',
      readiness: 98,
      status: 'Ready',
      regime: 'Bull',
      passed: ['Bias', 'Momentum', 'Breadth'],
      failed: ['None'],
      reason: 'Bias and participation aligned.',
      nextEvaluation: 'in 15 minutes',
    },
    {
      rank: 2,
      symbol: 'ETH',
      primaryStrategy: 'Mean Reversion',
      secondaryStrategy: 'VWAP Reclaim',
      readiness: 95,
      status: 'Near Ready',
      regime: 'Bull',
      passed: ['Regime', 'Liquidity'],
      failed: ['Trigger candle'],
      reason: 'Waiting for the last ignition key.',
      nextEvaluation: 'in 15 minutes',
    },
    {
      rank: 3,
      symbol: 'SOL',
      primaryStrategy: 'Momentum',
      secondaryStrategy: 'Trend Continuation',
      readiness: 91,
      status: 'Data Stale',
      regime: 'Bull',
      passed: ['Regime'],
      failed: ['Fresh candle'],
      reason: 'Signal withheld because the candle worker is the lone bar-writer.',
      nextEvaluation: 'after next sync',
    },
  ],
  strategyLeaderboard: {
    stocks: [
      { rank: 1, symbol: 'NVDA', score: 97 },
      { rank: 2, symbol: 'AAPL', score: 94 },
      { rank: 3, symbol: 'PLTR', score: 89 },
      { rank: 4, symbol: 'MSFT', score: 86 },
    ],
    crypto: [
      { rank: 1, symbol: 'BTC', score: 98 },
      { rank: 2, symbol: 'ETH', score: 95 },
      { rank: 3, symbol: 'SOL', score: 91 },
      { rank: 4, symbol: 'ADA', score: 84 },
    ],
  },
  logs: [
    {
      id: 1,
      timestamp: '2026-03-14 14:32:31',
      level: 'INFO',
      component: 'Trade Engine',
      source: 'User (Alert)',
      action: 'Place Order ETH',
      status: 'SUCCESS',
      symbol: 'ETH',
      payload: '{"order_id":"ord_1042","risk_pct":0.85}',
      chain: 'signal → risk → execution → audit',
      message: 'Order accepted after fee-aware and slippage-aware validation.',
    },
    {
      id: 2,
      timestamp: '2026-03-14 14:31:35',
      level: 'WARN',
      component: 'Market Data Feed',
      source: 'Kraken',
      action: 'Freshness Alert',
      status: 'ALERT',
      symbol: 'SOL',
      payload: '{"freshness_minutes":18}',
      chain: 'candle worker → freshness tracker → ui alert',
      message: 'SOL incremental sync lagged past the freshness threshold.',
    },
    {
      id: 3,
      timestamp: '2026-03-14 14:29:10',
      level: 'INFO',
      component: 'Universe Scanner',
      source: 'System (Auto)',
      action: 'Universe Refresh',
      status: 'DONE',
      symbol: '',
      payload: '{"source":"ai","symbols":42}',
      chain: 'ai universe → fallback guard → publish universe',
      message: 'Universe refreshed from AI source with fallback idle.',
    },
    {
      id: 4,
      timestamp: '2026-03-14 14:28:14',
      level: 'CRIT',
      component: 'Security Module',
      source: 'System',
      action: 'Kill Switch Test',
      status: 'SUCCESS',
      symbol: '',
      payload: '{"enabled":false,"test":true}',
      chain: 'settings → controls api → audit event',
      message: 'Kill switch test completed and reset cleanly.',
    },
  ],
  settings: {
    left: [
      { label: 'Kraken live', type: 'toggle', value: true, defaultValue: 'Off', lastChanged: '3m ago' },
      { label: 'Public live', type: 'toggle', value: false, defaultValue: 'Off', lastChanged: '12m ago' },
      { label: 'Alpaca stock paper', type: 'toggle', value: true, defaultValue: 'On', lastChanged: '15m ago' },
      { label: 'Alpaca crypto paper', type: 'toggle', value: true, defaultValue: 'On', lastChanged: '15m ago' },
      { label: 'Per-venue trading enabled', type: 'toggle', value: true, defaultValue: 'On', lastChanged: '2h ago' },
      { label: 'Default allocation by asset class', type: 'value', value: 'Manage...', defaultValue: 'Split', lastChanged: '1d ago' },
    ],
    middle: [
      { label: 'Read-only mode', type: 'toggle', value: false, defaultValue: 'Off', lastChanged: '4h ago' },
      { label: 'Settled-cash only', type: 'toggle', value: true, defaultValue: 'On', lastChanged: '1d ago' },
      { label: 'Preset crypto control', type: 'value', value: 'Moderate', defaultValue: 'Moderate', lastChanged: '5h ago' },
      { label: 'Per-venue rate limit', type: 'value', value: '10', defaultValue: '10', lastChanged: '6h ago' },
      { label: 'Default risk per trade', type: 'value', value: '1.25%', defaultValue: '1.00%', lastChanged: '3h ago' },
      { label: 'Stock deployment cap', type: 'value', value: '90%', defaultValue: '90%', lastChanged: '2d ago' },
    ],
    right: [
      { label: 'Position sizing enabled', type: 'toggle', value: true, defaultValue: 'On', lastChanged: '3h ago' },
      { label: 'Strategy throttles enabled', type: 'toggle', value: true, defaultValue: 'On', lastChanged: '4h ago' },
      { label: 'Execution enabled', type: 'toggle', value: true, defaultValue: 'On', lastChanged: '4h ago' },
      { label: 'Settled cash only', type: 'toggle', value: true, defaultValue: 'On', lastChanged: '4h ago' },
      { label: 'Live / paper mode', type: 'value', value: 'Mixed', defaultValue: 'Paper', lastChanged: '20m ago' },
      { label: 'Universe source', type: 'value', value: 'AI with fallback', defaultValue: 'Legacy', lastChanged: '18m ago' },
    ],
  },
};
